site_name: Kairon Documentation
site_description: AI-powered research assistant documentation
site_author: Akash Ajay Kallai
site_url: https://akash2704.github.io/kairon

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.integrate

repo_name: akash2704
repo_url: https://github.com/akash2704/Advanced-AI-Research-System

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference:
    - Research Agent: api/research_agent.md
    - Draft Agent: api/draft_agent.md
    - Quality Agent: api/quality_agent.md
    - Orchestrator: api/orchestrator.md
  - Contributing: contributing.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde 
